{
 "title": "VA Main Router",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Пиковые часы загрузки ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(\r\n  sum(rate(interface_if_in_octets[5m]))[1h:1h]\r\n) / 1000000",
     "legendFormat": "Входящий трафик"
    },
    {
     "expr": "avg_over_time(\r\n  sum(rate(interface_if_out_octets[5m]))[1h:1h]\r\n) / 1000000",
     "legendFormat": "Исходящий трафик"
    }
   ]
  },
  {
   "title": "Текущая скорость свича",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum(rate(interface_if_in_octets[1m])) / 1000000",
     "legendFormat": "Весь входящий трафик"
    },
    {
     "expr": "sum(rate(interface_if_out_octets[1m])) / 1000000",
     "legendFormat": "Весь исходящий трафик"
    }
   ]
  },
  {
   "title": "Использование памяти ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "memory_system_system_usage_kb / 1024",
     "legendFormat": "Slot {{slot_id}} - Система"
    },
    {
     "expr": "memory_system_user_usage_kb / 1024",
     "legendFormat": "Slot {{slot_id}} - Пользователи"
    }
   ]
  },
  {
   "title": "Трафик по всем интерфейсам",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(interface_if_in_octets[1m]) / 1000000",
     "legendFormat": "{{if_descr}} - Входящий"
    },
    {
     "expr": "rate(interface_if_out_octets[1m]) / 1000000",
     "legendFormat": "{{if_descr}} - Исходящий"
    }
   ]
  },
  {
   "title": "Загруженность памяти в процентах",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((memory_system_system_usage_kb + memory_system_user_usage_kb) / memory_system_total_kb) * 100",
     "legendFormat": "Слот {{slot_id}} "
    }
   ]
  },
  {
   "title": "Загрузка CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "snmp_cpu_total_usage",
     "legendFormat": "Загрузка процессора в процентах"
    }
   ]
  },
  {
   "title": "Температура ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "snmp_temperature", "legendFormat": "Volue" }
   ]
  },
  {
   "title": "Статусы портов",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(interface_if_oper_status == 1)",
     "legendFormat": "UP"
    },
    {
     "expr": "count(interface_if_oper_status == 2)",
     "legendFormat": "DOWN"
    }
   ]
  }
 ]
}